### ISSUE TITLE
Some question about how to run the code

### ISSUE THREAD

**Issue by handsomelys** [acolas1/KGSimple#1]
Your work is interesting and I'm interested! But I'm curious about how the code of this repo needs to run, can you give the specific steps in the README?

**Comment by mhd0528** [comment]
Hi, thanks for the interest! We will release the scripts to run the whole model soon. Still re-organizing the codebase

**Comment by acolas1** [comment]
Hi, thanks again for your interest in our work! We have updated the README with the instructions on how to run our model. Feel free to let us know if you need any other clarifications.
